name: Force Destroy Everything in AWS

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type "FORCE_DESTROY" to confirm destruction'
        required: true

jobs:
  force_destroy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirm_destroy == 'FORCE_DESTROY' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init
        
      - name: Terraform destroy details
        run: terraform plan -destroy

      - name: Force Destroy Everything
        run: terraform destroy -auto-approve || echo "Terraform destroy failed, please check manually."

      - name: Cleanup Confirmation
        run: echo "✅ All AWS resources have been force destroyed."
