name: Manual Terraform Destroy

on:
  workflow_dispatch:  # Manually trigger the workflow

env:
  AWS_REGION: ap-southeast-1  # Define the AWS region for the resources

jobs:
  CICD:
    runs-on: ubuntu-latest  # Define the runner environment

    steps:
    - name: Checkout
      uses: actions/checkout@v3  # Check out the repository code

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1  # Configure AWS credentials
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Use stored secrets
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Use stored secrets
        aws-region: ${{ env.AWS_REGION }}  # Use the defined AWS region

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2  # Setup Terraform on the runner

    - name: Terraform Init
      run: terraform init  # Initialize Terraform configuration

    - name: Terraform Destroy
      run: terraform destroy --auto-approve  # Destroy the resources with auto-approve