name: Select To Destroy

on:
  workflow_dispatch:  
    inputs:
      tfstate_key:
        description: "Select the Terraform state file to destroy"
        required: true
        default: "tf-ce8_capstone_yyf_Nonprod.tfstate"
        type: choice
        options:
          - "tf-ce8_capstone_yyf_prod.tfstate"
          - "tf-ce8_capstone_yyf_Nonprod.tfstate"

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: Destroy AWS Resources
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Initialize Terraform Backend with Selected State File
        run: |
          terraform init -reconfigure -backend-config="bucket=sctp-ce8-tfstate" \
            -backend-config="key=${{ github.event.inputs.tfstate_key }}" \
            -backend-config="region=ap-southeast-1"

      - name: List Terraform State Resources
        run: terraform state list || echo "No state file found"

      - name: Destroy AWS Resources
        run: terraform destroy -auto-approve
